Migrate to Vuepress
inversify/inversify.github.io pull request #17
Opened 2021-05-06 20:48 UTC by LeonardSSH

Closes #16

2021-05-07 09:22 UTC, notaphplover requested changes
Looks great! I requested some changes. We should probably think how to control the internationalization coverage.

2021-05-07 09:22 UTC, notaphplover commented on CNAME
> -inversify.io
Should we remove this file? I think it's used by GH to [link the subdomain](https://docs.github.com/es/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain).

2021-05-07 09:22 UTC, notaphplover commented on ISSUE_TEMPLATE.md
> -THANKS!
I think this file should not be removed

2021-05-07 09:22 UTC, notaphplover commented on src/.vuepress/theme/components/NavLinks.vue
> +      }
We are returning twice the language dropdown here. I think we should try to replace it instead of returning a duplicate

2021-05-07 09:23 UTC, notaphplover commented on package.json
> +		"email": ""
We should keep the original author here

2021-05-07 12:53 UTC, LeonardSSH commented
updated preview link.

2022-01-27 13:43 UTC, PodaruDragos commented
hey @LeonardSSH @dcavanagh @notaphplover do we not want to merge this ?
I remember the preview looked great

2022-01-27 13:47 UTC, LeonardSSH commented
@PodaruDragos I need to take a little look at what I did last time, I know there were little problems, maybe I'll replace Vuepress with Vitepress. I also need to get in touch with whoever now owns the actual deployment for the website, so I know what to do.

2025-01-26 23:51 UTC, notaphplover commented
Closing as new docusaurus docs are provided instead

2025-01-26 23:51 UTC, closed without merging